imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    wgrib2_path: /usr/local/bin/wgrib2
    vdifn.cache_dir: %kernel.cache_dir%/vdifn
    vdifn.noaa.predicted.url.data_file: http://www.ftp.ncep.noaa.gov/data/nccf/com/nam/prod/nam.%%s/nam.t00z.awip12%%s.tm00.grib2
    vdifn.noaa.predicted.path.data_file: %vdifn.cache_dir%/%%s/nam.t00z.awip12%%s.tm00.grib2
    # Correspond to the record number in this inventory: http://www.nco.ncep.noaa.gov/pmb/products/nam/nam.t00z.awip1200.tm00.grib2.shtml
    vdifn.noaa.predicted.fields: [11, 12, 13, 14, 18, 24, 28, 76, 118, 159]
    vdifn.noaa.predicted.hours: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84]
    # Only data for these states will be imported
    vdifn.noaa.predicted.states: [Wisconsin]
    vdifn.state.class: PlantPath\Bundle\VDIFNBundle\Service\StateService
    # Leaf-wetting time relative humidity threshold
    vdifn.lwt_rh_threshold: 85
    # Only data within this bounding box will be imported
    vdifn.bounding_box.n: 47.408574
    vdifn.bounding_box.e: -85.649414
    vdifn.bounding_box.s: 42.125729
    vdifn.bounding_box.w: -93.757324
    vdifn.admin.email: { 'admin@vdifn.net': 'VDIFN Admin' }
    vdifn.admin.emails: [dwieeb@gmail.com]
    vdifn.date_format: '{yyyy}{MM}{dd}'
    vdifn.google_maps.api_key: 'AIzaSyDWBHf90rmieg96Wx7UgGmaJxylc6ML_Bs'
    vdifn.google_maps.sensor: 'false'

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        parameters:
            debug: %kernel.debug%
            admin_email: admin@vdifn.net
            date_format: %vdifn.date_format%
            bounding_box:
                n: %vdifn.bounding_box.n%
                e: %vdifn.bounding_box.e%
                s: %vdifn.bounding_box.s%
                w: %vdifn.bounding_box.w%
            google_maps:
                api_key: %vdifn.google_maps.api_key%
                sensor: %vdifn.google_maps.sensor%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ PlantPathVDIFNBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            utcdatetime: PlantPath\Bundle\VDIFNBundle\Type\UTCDateTimeType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
