plant_path_vdifn:
    resource: "@PlantPathVDIFNBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

user_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }
    options:
        expose: true

user_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    options:
        expose: true

user_register:
    pattern:  /register
    defaults: { _controller: FOSUserBundle:Registration:register }
    options:
        expose: true

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
