parameters:
    wgrib2_path: /usr/local/bin/wgrib2
    vdifn.cache_dir: %kernel.cache_dir%/vdifn
    vdifn.noaa_url: http://www.ftp.ncep.noaa.gov/data/nccf/com/nam/prod/nam.%%s/nam.t00z.awip12%%s.tm00.grib2
    vdifn.noaa_path: %vdifn.cache_dir%/%%s/nam.t00z.awip12%%s.tm00.grib2
    # Correspond to the record number in this inventory: http://www.nco.ncep.noaa.gov/pmb/products/nam/nam.t00z.awip1200.tm00.grib2.shtml
    vdifn.noaa_fields: [11, 12, 13, 14, 18, 24, 28, 76, 118, 159]
    vdifn.noaa_hours: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84]
    # Only data for these states will be imported
    vdifn.noaa_states: [Wisconsin]
    vdifn.state.class: PlantPath\Bundle\VDIFNBundle\Service\StateService
    # Leaf-wetting time relative humidity threshold
    vdifn.lwt_rh_threshold: 85
    # Only data within this bounding box will be imported
    vdifn.bounding_box.coordinates.n: 47.408574
    vdifn.bounding_box.coordinates.e: -85.649414
    vdifn.bounding_box.coordinates.s: 42.125729
    vdifn.bounding_box.coordinates.w: -93.757324
