services:
    raven:
        class: Raven_Client
        arguments:
            dsn: %vdifn.sentry_dsn%
    vdifn.state:
        class: %vdifn.state.class%
    kernel.listener.command_dispatch:
        class: PlantPath\Bundle\VDIFNBundle\EventListener\ConsoleExceptionListener
        arguments:
            logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: console.exception }
